site_name: "Tech Chronicles: Resilient Code Tales, Failures & Learnings"
site_author: "Abir Hasan Munna"

nav:
  - Home: index.md 
  - Abir: 
    - 'Abir/about.md'
    - FastAPI:
      - 'FastAPI in minutes': 'Abir/FastAPI/intro.md'
      - 'FastAPI in minutes(extended)': 'Abir/FastAPI/todo_l1.md'

theme:
  name: material
  logo: assets/hacker.png
  favicon: assets/hacker.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    
  language: en
  
  font:
    text: Roboto
    code: Roboto Mono


  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode    
      primary: teal
      accent: lime


extra:
  generator: false

plugins: 
  - search
  - open-in-new-tab


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/abirmunna"  target="_blank" rel="noopener">Abir Hasan Munna</a>